# See: https://jekyllrb.com/docs/configuration/
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme

# Site settings
title: Yuri's Licenses
description: Open Source license templates created by Yuri
show_downloads: "true"